[[book]]
isbn = "9781250301130"
readDate = "2024-06-07"
score = 4

[[book]]
isbn = "9781529115543"
readDate = "2024-07-22"
score = 3

[[book]]
isbn = "9780316556330"
readDate = "2024-08-01"
score = 5

[[book]]
isbn = "9780062319654"
readDate = "2024-08-03"
score = 5

[[book]]
isbn = "9780143039983"
readDate = "2024-08-30"
score = 2

[[book]]
# isbn = "9780736674980"
isbn = "9780739358047"
readDate = "2024-11-30"
score = 5

[[book]]
isbn = "9780060959470"
readDate = "2025-01-25"
score = 3

[[book]]
isbn = "9780241988275"
readDate = "2025-02-13"
score = 4

[[book]]
isbn = "9782981912855"
readDate = "2025-02-15"
score = 4

[[book]]
isbn = "9780156030083"
readDate = "2025-02-22"
score = 4

[[book]]
isbn = "9780765397539"
readDate = "2025-06-05"
score = 5

[[book]]
isbn = "9781250186935"
readDate = "2025-06-21"
score = 5

[[book]]
isbn = "9781447273318"
readDate = "2025-08-29"
score = 4

[[book]]
isbn = "9781784752224"
readDate = "2025-10-17"
score = 4

[[book]]
isbn = "9780525562023"
readDate = "2025-11-13"
score = 4
